-- AlterTable
ALTER TABLE `user` ADD COLUMN `email` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `firstname` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `lastname` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `middle` VARCHAR(191) NOT NULL DEFAULT '';
