-- AlterTable
ALTER TABLE `user` ADD COLUMN `barangay` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `city` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `province` VARCHAR(191) NOT NULL DEFAULT '';
